interface Env {
  DB: D1Database;
  CRABYARD_BOOTSTRAP_TOKEN?: string;
  GITHUB_CLIENT_ID?: string;
  GITHUB_CLIENT_SECRET?: string;
  GITHUB_ORG?: string;
  GITHUB_TOKEN?: string;
  CRABYARD_INTERACTIVE_PROVISION_URL?: string;
  CRABYARD_INTERACTIVE_PROVISION_TOKEN?: string;
}
